services:
  eureka-server:
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    ports:
      - '8761:8761'
  gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - '9890:9890'
    depends_on: 
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761
      #SPRING_CLOUD_CONFIG_URI: http://config-server:8888
  postgres:
    image: 'postgres'
    restart: always
    environment:
      - 'POSTGRES_DB=settings-service'
      - 'POSTGRES_PASSWORD=donald'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - postgresql_data:/var/lib/postgresql/data
      
  pgadmin4:
    image: 'elestio/pgadmin'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: donald9do@gmail.com
      PGADMIN_DEFAULT_PASSWORD: donald
      PGADMIN_LISTEN_PORT: 4000
    ports:
      - '4000:4000'
    volumes:
      - ./servers.json:/pgadmin4/servers.json
  sonarqube:
    image: sonarqube:community
    depends_on:
      - postgres
    environment:
      - sonar.jdbc.username=donald
      - sonar.jdbc.password=donald
      - sonar.jdbc.url=jdbc:postgresql://db/sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
 ## prometheus:
  #  image: bitnami/prometheus
 #   container_name: prometheus
  #  command:
  #    - '--config.file=/etc/prometheus.yml'
  #  ports:
  #    - 9090:9090
  #  restart: unless-stopped
  #  volumes:
  #    - ./prometheus:/etc/prometheus
  #grafana:
  #  image: grafana/grafana
  #  ports:
  #    - "3000:3000"
  #  volumes:
  #    - ./grafana/tmp:/var/lib/grafana

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: